### ISSUE TITLE
UI bug: Main page - workflows now running gets stuck at 1

### ISSUE THREAD

**Issue by agardelakos** [panoptes-organization/panoptes#42] opened 2019-11-20 16:49 UTC
when a local run (from snakemake-example-workflow) is performed and the results folder is already present, the badge "workflows now running" in panoptes main page always shows 1 and the badge "workflows executed" never gets populated.

Expected behaviour: even in that corner case, the main page should populate the badges correctly.

**Comment by fgypas** [comment] 2019-11-27 21:10
relates to #51

**Comment by fgypas** [comment] 2020-02-04 11:51
I think this is fixed in 2b5125a9d196e6afef9bf561e5c116135b6b435c

**Comment by fgypas** [comment] 2020-02-05 19:15
I am re-opening. The issue is still there.

**Comment by fgypas** [comment] 2020-02-05 19:19
The log that is passed in such cases is:

`{'msg': "{'level': 'info', 'msg': 'Nothing to be done.', 'indent': False}", 'timestamp': 'Wed Feb  5 20:17:49 2020', 'id': 6}`

**Closed** 2020-02-05 21:26 UTC
Labels: bug, enhancement
